import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local';
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const clashDisplay = localFont({
  // Add an 's' to 'font' to make it 'fonts'
  src: './fonts/ClashDisplay-Variable.woff2', 
  display: 'swap',
  variable: '--font-clash-display',
});
const SwitDisplay = localFont({
  // Add an 's' to 'font' to make it 'fonts'
  src: './fonts/Switzer-VariableItalic.woff2', 
  display: 'swap',
  variable: '--font-swit-display',
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}  ${clashDisplay.variable} ${SwitDisplay.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
